##     / \__
##    (    @\__ 
##    /         O
##   /   (_____/
##  /_____/   U                                   
##                      github.com/tagirov/HuskyOS
##################################################

theme = "synthwave"

[editor]
bufferline = "always"
soft-wrap.enable = true
lsp.enable = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
"'" = "'"
'<' = '>'

[keys.normal]
g = { n = "goto_line_start", o = "goto_line_end" }

# "C-," = ":!lua ~/.config/helix/toggle_comment_html.lua<CR>"

"щ" = "yank"
"ы" = "paste_after"
"h" = ":buffer-next"
"j" = ":buffer-previous"
# "k" = "append_mode"

"," = "open_below"
"<" = "open_above"

"C-s" = ":w"
"C-q" = ":q"
"C-a" = ":bc"
"C-r" = ":buffer-close!"
"C-y" = ":pipe llm"
"C-j" = ":toggle soft-wrap.enable"
"C-p" = ":reflow"

X = "extend_line_above"
n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"
l = "insert_mode"
L = "insert_at_line_start"
A = "insert_at_line_end"

"}" = "move_next_word_end"
"{" = "move_next_long_word_end"

")" = "search_next"
"(" = "search_prev"

C-b = "jump_backward"
C-k = "jump_forward"
C-m = "save_selection"

## Turbo navigation

C-n = [
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
]
C-o = [
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
]
C-i = [
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
]
C-e = [
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]

[keys.insert]
C-s = ":w"
C-q = ":q"
"C-a" = ":bc"
"C-r" = ":buffer-close!"

C-n = [
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
]
C-o = [
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
]
C-i = [
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
]
C-e = [
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]

[keys.select]
l = "insert_mode"

g = { n = "goto_line_start", o = "goto_line_end" }

C-s = ":w"
C-q = ":q"
"C-a" = ":bc"
"C-r" = ":buffer-close!"
"C-y" = ":pipe llm"

n = "move_char_left"
e = "move_line_down"
i = "move_line_up"
o = "move_char_right"

j = "search_next"
J = "search_prev"

C-n = [
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
  "move_char_left",
]
C-o = [
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
  "move_char_right",
]
C-i = [
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
  "move_line_up",
]
C-e = [
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
  "move_line_down",
]
